function FinalData1 = load_gwynt_y_mor(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FINALDATA1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  FINALDATA1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  FinalData1 = importfile("C:\Users\carlo\Documents\EWEM MSc\DTU 2021\46200 - Wind Farm Planning and Design\Case Study\FinalData.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Jan-2022 10:54:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Year", "Month", "Day", "minout", "MAnemoMean", "MAnemoStdDev", "MWVMean", "MWVStdDev", "MTempMean", "MPressMean"];
opts.SelectedVariableNames = ["Year", "Month", "Day", "minout", "MAnemoMean", "MAnemoStdDev", "MWVMean", "MWVStdDev", "MTempMean", "MPressMean"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
FinalData1 = readtable(filename, opts);

%% Convert to output type
FinalData1 = table2array(FinalData1);
end